# Smooth Overlap of Atomic Positions

SOAP is a **local** descriptor, that maps the local environment around a point very accurately. It eliminates rotational, and permutation redundancies by integrating the overlap of smoothed out atomic positions, by gaussian smearing, and mapping them into coefficients of orthornormal basis functions.

This is done by the following steps:

* Smooth out the atomic positions:

    The atomic positions are point objects in space. Integrating them would need a lot of basis functions. Thus, the atoms' positions are smeared as gaussian functions. 
    $$ \rho(r) = \sum_i e^{-(r-r_i)^2}$$
    However, this also makes all the elements indistinguishable. Thus, SOAP for individual elements, in molecule/unit-cell, is calculated, and then the values are concantenated at end. 
    ![soap depiction](https://github.com/reinimaurer1/ML-CSC-tutorial/blob/master/images/soap_depiction.png?raw=1) *Image courtesy Jäger Marc*


* Generate orthonormal basis set:

    The obtained smeared atomic position, or atomic density, if you will, is decomposed using Laplace Spherical Harmonics -- spherical harmonics in real space -- and orthogonal basis set: $\Upsilon_{lm}(\theta, \phi)$ and  $g_n(r) $. 
    Basis function for s orbital of hydrogen: ![basis function](https://github.com/reinimaurer1/ML-CSC-tutorial/blob/master/images/basis_set.jpg?raw=1) 
    Laplace spherical harmonics $\Upsilon_{ℓm}$ for l = 0, …, 4 (top to bottom) and m = 0, …, l (left to right). The negative order harmonics $\Upsilon_{ℓ-m}$ would be shown rotated about the z axis by $90^o$ with respect to the positive order ones.
    ![rotating spherical harminics](https://github.com/reinimaurer1/ML-CSC-tutorial/blob/master/images/Rotating_spherical_harmonics.gif?raw=1)  *Image courtsey wikipedia.org/wiki/User:Cyp*  
    

* Integrate for all coefficients:
    $$c_{nlm} = \left< \rho | g_n(r)\Upsilon_{lm} \right>  = \int_V g_n(r)\Upsilon_{lm}(\theta, \phi)\rho(r, \theta, \phi)dV$$
    Further, a power spectrum, or a density matrix, per se, is made out of these parameters and summed for all m's for rotational invarience.
    $$P_{nn'l} = \sum_m c_{nlm}c^*_{n'lm}$$
    

For more info see:
[Bartók, Albert P., Risi Kondor, and Gábor Csányi. <i>Physical Review B 87.18</i> (2013): <b>184115</b>](https://arxiv.org/pdf/1209.3140.pdf;)

For calculating SOAP, we use the [DScribe package](https://singroup.github.io/dscribe) as developed by [Surfaces and Interfaces at the Nanoscale, Aalto](http://physics.aalto.fi/en/groups/sin/)

## Example

We are going to see SOAP in action for a simple NaCl system.

In [1]:
!pip install ase
!pip install dscribe
!git clone https://github.com/reinimaurer1/ML-CSC-tutorial tut
!mv tut/data data
# --- INITIAL DEFINITIONS ---
import numpy, math, random
from ase.visualize import view
from ase import Atoms
import sys
sys.path.insert(0, './data/descriptor_codes/')
sys.path.insert(0, './data/descriptor_codes/src')
from dscribe.descriptors import SOAP

     |████████████████████████████████| 2.2 MB 5.3 MB/s 
     |████████████████████████████████| 143 kB 4.9 MB/s 
  Using cached pybind11-2.7.1-py2.py3-none-any.whl (200 kB)
     |████████████████████████████████| 76 kB 3.5 MB/s 
  Created wheel for dscribe: filename=dscribe-1.1.0-cp37-cp37m-linux_x86_64.whl size=4339789 sha256=12e2c1722481a1b6a99cee7fd1ce5da5992d1ebde25f3728335e24f01b977c23
  Stored in directory: /root/.cache/pip/wheels/05/f8/a6/c5328c447d56d1efed920c372cbd0086ac1e01de1b5adaa9db
Successfully built dscribe
Cloning into 'tut'...
remote: Enumerating objects: 393, done.
remote: Counting objects: 100% (76/76), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 393 (delta 37), reused 16 (delta 5), pack-reused 317
Receiving objects: 100% (393/393), 543.18 MiB | 35.92 MiB/s, done.
Resolving deltas: 100% (160/160), done.
Checking out files: 100% (129/129), done.


### Atom description

We'll make an ase.Atoms class for NaCl:

In [2]:
# Define the system under study: NaCl in a conventional cell.
NaCl_conv = Atoms(
    cell=[
        [5.6402, 0.0, 0.0],
        [0.0, 5.6402, 0.0],
        [0.0, 0.0, 5.6402]
    ],
    scaled_positions=[
        [0.0, 0.5, 0.0],
        [0.0, 0.5, 0.5],
        [0.0, 0.0, 0.5],
        [0.0, 0.0, 0.0],
        [0.5, 0.5, 0.5],
        [0.5, 0.5, 0.0],
        [0.5, 0.0, 0.0],
        [0.5, 0.0, 0.5]
    ],
    symbols=["Na", "Cl", "Na", "Cl", "Na", "Cl", "Na", "Cl"],
)
view(NaCl_conv)

### Setting SOAP hyper-parameters
Next we set the hyper-parameters to SOAP. 
1. calcpos, center of SOAP calculation
1. rcut, sets the cutoff for atoms whose gaussian densities will be included in the integral.
2. nmax, sets the number of orthogonal radial basis functions to use.
3. lmax, sets the number of angular momentum terms, so l = 0, 1, ...., lmax

    **Note: even when giving one SOAP calculation position, it should be wrapped in a list, as shown in example below**

In [3]:
# Computing SOAP
calcpos = [0, 0, 0]

soaper = SOAP(
    rcut=8,
    nmax=5,
    lmax=5,
    species=['Na', 'Cl'],
    sparse=False
)

### Calculation
Now we call the soap function, and pass all the parameters

In [4]:
#calculation
soap1 = soaper.create(NaCl_conv, positions=[calcpos])
print("Size of descriptor: {}".format(soap1.shape[1]))
print("First five values, for position {}: {}".format(calcpos, soap1[0,:5]))

Size of descriptor: 330
First five values, for position [0, 0, 0]: [ 1.31417503e-05  2.05252113e-03  3.99968684e-03 -1.00371139e-02
 -2.71834549e-02]


### Rotational invariance

In [5]:
#Rotation of positions

print("Original positions:\n {}".format(NaCl_conv.positions))

NaCl_conv.rotate(90, [0,1,1], center=calcpos)

print("Rotated positions:\n {}".format(NaCl_conv.positions))

view(NaCl_conv)

Original positions:
 [[0.     2.8201 0.    ]
 [0.     2.8201 2.8201]
 [0.     0.     2.8201]
 [0.     0.     0.    ]
 [2.8201 2.8201 2.8201]
 [2.8201 2.8201 0.    ]
 [2.8201 0.     0.    ]
 [2.8201 0.     2.8201]]
Rotated positions:
 [[-1.99411183e+00  1.41005000e+00  1.41005000e+00]
 [ 0.00000000e+00  2.82010000e+00  2.82010000e+00]
 [ 1.99411183e+00  1.41005000e+00  1.41005000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.72681322e-16  4.81421183e+00  8.25988166e-01]
 [-1.99411183e+00  3.40416183e+00 -5.84061834e-01]
 [ 1.72681322e-16  1.99411183e+00 -1.99411183e+00]
 [ 1.99411183e+00  3.40416183e+00 -5.84061834e-01]]


Recompute SOAP for the same atom, after rotation and show the difference in descriptors:

In [6]:
soap2 = soaper.create(NaCl_conv, positions=[calcpos])
print(numpy.linalg.norm(soap1 - soap2))

4.1953580838919973e-13


## Remark

The power spectrum at a desired position x is the fingerprint of the local chemical environment at this specific position. Thus, it can be used to:
1. Compare the similarity of two local chemical environments by comparing their SOAP descriptors.
2. Machine learn local properties, like charges, adsorption energies, etc.

## Exercises

### 1. Smoothness

Verify that the SOAP is smooth under translations of point of interest.

In [7]:
# DIY...

### 2. Construct a global SOAP
Use the atomic environments to construct an average SOAP descriptor for molecules

In [8]:
# atomic positions as matrix
molxyz = numpy.load("./data/molecule.coords.npy")
# atom types
moltyp = numpy.load("./data/molecule.types.npy")

atoms_sys = Atoms(positions=molxyz, numbers=moltyp)
view(atoms_sys)

In [ ]:
# build SOAP at each atom location
# ...
# compute average soap for each specie
# ...
# concatenate the soaps to the the overall global one
# ...